In [1]:
import pandas as pd
import seaborn as sns

In [7]:
df = pd.read_csv("heat_cost.csv")

In [11]:
df

,Country,range,Gas condensing boiler (2019 gas prices),Gas condensing boiler (gas prices 30% higher than 2019),Pellet boiler,Electric air-air heat pump,Electric air-water heat pump,Electric ground-source heat pump,Solar thermal combi system,Solar thermal water heat
0,Canada,low,31,33,113,47,48,29,43,49
1,Canada,high,48,55,163,90,82,52,106,150
2,Denmark,low,82,99,121,98,87,57,57,69
3,Denmark,high,133,160,204,163,142,89,99,167
4,France,low,91,108,142,73,81,53,85,143
5,France,high,143,169,284,197,170,94,206,309
6,Germany,low,72,91,163,118,111,64,58,98
7,Germany,high,125,153,290,207,184,109,123,237
8,United Kingdom,low,57,68,171,117,97,64,72,140
9,United Kingdom,high,97,113,298,183,145,104,135,277
10,Sweden,low,124,148,148,43,76,44,74,128
11,Sweden,high,193,229,228,78,127,70,153,310

In [12]:
df_mean = df.groupby("Country").mean()
df_mean

,Gas condensing boiler (2019 gas prices),Gas condensing boiler (gas prices 30% higher than 2019),Pellet boiler,Electric air-air heat pump,Electric air-water heat pump,Electric ground-source heat pump,Solar thermal combi system,Solar thermal water heat
Country,,,,,,,,
Canada,39.5,44.0,138.0,68.5,65.0,40.5,74.5,99.5
Denmark,107.5,129.5,162.5,130.5,114.5,73.0,78.0,118.0
France,117.0,138.5,213.0,135.0,125.5,73.5,145.5,226.0
Germany,98.5,122.0,226.5,162.5,147.5,86.5,90.5,167.5
Sweden,158.5,188.5,188.0,60.5,101.5,57.0,113.5,219.0
United Kingdom,77.0,90.5,234.5,150.0,121.0,84.0,103.5,208.5

In [13]:

# sns.barplot(x=df_mean.index)
sns.set_style("whitegrid")
sns.catplot(x="Country", y="Electric air-air heat pump", data=df_mean)

ValueError: Could not interpret input 'Country'